apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mysql
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: web-application
        image: 837853736685.dkr.ecr.us-east-1.amazonaws.com/mysql:1.1
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: pw
        ports:
        - containerPort: 3306
