apiVersion: v1
kind: Pod
metadata:
  name: web-application
spec:
  containers:
  - name: web-application
    image: 837853736685.dkr.ecr.us-east-1.amazonaws.com/app:1.0
    env:
     - name: DBHOST
       value: "mysql"
     - name: DBPORT
       value: "3306"
     - name: DBUSER
       value: "root"
     - name: DBPWD
       value: "pw"
     - name: APP_COLOR
       value: "pink"
    ports:
    - containerPort: 8080