name: build images and push to ECR

on:
  push:
    branches:
      - master

env:
  AWS_REGION: us-east-1
      
jobs:
  build:
    name: build and deploy image to AWS ECR
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Login to AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ env.AWS_REGION }}
          aws_session_token:  ${{ secrets.AWS_SESSION_TOKEN }}
          
          
      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v1
        
      - name: Build Docker image
        run: |
          docker build -t ${{ env.AWS_REGION }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/app:latest -f Dockerfile
  
      - name: Push Docker image
        run: |
          docker push ${{ env.AWS_REGION }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/app:latest
          echo "push the app image to ECR"