apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  namespace: final
  labels:
    app: flask-app
spec:
  selector:
    matchLabels:
      app: flask-app
  replicas: 1
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      serviceAccountName: clo835
      containers:
      - name: flask-app
        image: 837853736685.dkr.ecr.us-east-1.amazonaws.com/app:1.1
        env:
        - name: IMAGE_URL
          valueFrom: 
            configMapKeyRef:
              name: flask-app-cm
              key: IMAGE_URL
        - name: MY_NAME
          valueFrom: 
            configMapKeyRef:
              name: flask-app-cm
              key: MY_NAME
        - name: DBHOST
          valueFrom: 
            configMapKeyRef:
              name: flask-app-cm
              key: DBHOST
        - name: DBPORT
          valueFrom: 
            configMapKeyRef:
              name: flask-app-cm
              key: DBPORT
        - name: DBUSER
          valueFrom: 
            secretKeyRef:
              name: flask-app-secret
              key: DBUSER
        - name: DBPWD
          valueFrom: 
            secretKeyRef:
              name: flask-app-secret
              key: DBPWD
        ports:
        - containerPort: 81
      
            