---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: clo835-role-binding
subjects:
- kind: ServiceAccount
  name: clo835
  namespace: final
roleRef:
  kind: ClusterRole
  name: create-list-namespaces
  apiGroup: rbac.authorization.k8s.io